@startuml unnormalized_schema

entity Category_Категория {
    +id : int [PK]
    *name : str
    description : str
}

entity Brand_Бренд {
    +id : int [PK]
    *name : str
    description : str
}

entity Product_Товар {
    +id : int [PK]
    *name : str
    *price : float
    *age_limit : int
    *category_id : int [FK]
    *supplier_id : int [FK]
    *brand_id : int [FK]
}

entity Supplier_Поставщик {
    +id : int [PK]
    *name : str
    *address : str
}

entity Discount_Скидка {
    +id : int [PK]
    product_id : int [FK]
    category_id : int [FK]
    *percent : float
    *start_date : datetime.date
    *end_date : datetime.date
}

entity Supply_Поставка {
    +id : int [PK]
    *product_id : int [FK]
    *supplier_id : int [FK]
    *quantity : int
    *supply_date : datetime.date
    *supply_price : float
}

entity Role_Роль {
    +id : int [PK]
    *name : str
}

entity User_Пользователь {
    +id : int [PK]
    *name : str
    *email : str
    *phone : str
    *password : str
    *role_id : int [FK]
    passport_id : str
}

entity Order_Заказ {
    +id : int [PK]
    *customer_id : int [FK]
    *order_date : datetime.date
    *delivery_date : datetime.date
    *status : str
}

entity OrderItem_Элемент_Заказа {
    +id : int [PK]
    *order_id : int [FK]
    *product_id : int [FK]
    *quantity : int
    *total_price : float
}

entity Cart_Корзина {
    +id : int [PK]
    *customer_id : int [FK]
}

entity CartItem_Элемент_Корзины {
    +id : int [PK]
    *cart_id : int [FK]
    *product_id : int [FK]
    *quantity : int
}

entity Review_Отзыв {
    +id : int [PK]
    *customer_id : int [FK]
    *product_id : int [FK]
    *grade : int
    comment : str
}

entity ActivityLog_Лог_Действий {
    +id : int [PK]
    *user_id : int [FK]
    *action : str
    *date : datetime.date
    *time : datetime.time
}

Category_Категория ||--o{ Product_Товар : "1:M"
Brand_Бренд ||--o{ Product_Товар : "1:M"
Product_Товар ||--o{ Supply_Поставка : "1:M"
Supplier_Поставщик ||--o{ Supply_Поставка : "1:M"

Product_Товар ||--o{ Discount_Скидка : "1:M"
Category_Категория ||--o{ Discount_Скидка : "1:M"

User_Пользователь ||--o{ Order_Заказ : "1:M"
Order_Заказ ||--o{ OrderItem_Элемент_Заказа : "1:M"
Product_Товар ||--o{ OrderItem_Элемент_Заказа : "1:M"

User_Пользователь ||--|| Cart_Корзина : "1:1"
Cart_Корзина ||--o{ CartItem_Элемент_Корзины : "1:M"
Product_Товар ||--o{ CartItem_Элемент_Корзины : "1:M"

User_Пользователь ||--o{ Review_Отзыв : "1:M"
Product_Товар ||--o{ Review_Отзыв : "1:M"

User_Пользователь ||--o{ ActivityLog_Лог_Действий : "1:M"
User_Пользователь }o--|| Role_Роль : "M:1"

Supplier_Поставщик ||--o{ Product_Товар : "M:M"

@enduml
